name: f1
channels:
  - pkgs/main
dependencies:
  - python=3.9
  - pip
  - pip:
      - pip
      # dev
      - ipykernel
      - mypy
      - notebook
      - pydocstyle
        # app
      - pandas
      - requests
      - seaborn
      - matplotlib
      - types-requests
      - fastf1
      - pypath-magic
