name: f1
channels:
  - pkgs/main
dependencies:
  - python=3.9
  - conda-libmamba-solver
  - pip
  - pip:
      # dev
      - black
      - flake8
      - ipykernel
      - mamba
      - mypy
      - notebook
      - pydocstyle
      - pylint
        # app
      - pandas
      - requests
      - seaborn
      - matplotlib
      - types-requests
      - fastf1
      - pypath-magic
