name: f1
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=21
    # dev
  - black
  - flake8
  - ipykernel
  - mamba
  - mypy
  - notebook
  - pydocstyle
  - pylint
    # app
  - pandas==1.4.1
  - requests==2.27.1
  - seaborn==0.11.2
  - matplotlib==3.5.1
  - types-requests==2.27.14
  - pip:
      - fastf1==2.2.1
