name: f1
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=21
    # dev
  - black
  - flake8
  - ipykernel
  - mamba
  - mypy
  - notebook
  - pydocstyle
  - pylint
    # app
  - pandas
  - requests
  - seaborn
  - matplotlib
  - types-requests
  - pip:
      - fastf1
