name: f1
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=22
    # dev
  - black
  - flake8
  - ipykernel
  - mamba
  - mypy
  - notebook
  - pydocstyle
  - pylint
    # app
  - pandas
  - requests
  - seaborn
  - matplotlib
  - types-requests
  - pip:
      - fastf1
      - pypath-magic
