name: f1
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=21
  - pip:
      # devel
      - black
      - flake8
      - ipykernel
      - mypy
      - notebook
      - pydocstyle
      - pylint
      # F1
      - pandas==1.3.5
      - requests==2.26.0
      - fastf1==2.1.13
      - seaborn==0.11.2
      - matplotlib==3.5.1
